# Generated by Django 4.1.7 on 2023-07-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_merge_20230701_1808'),
        ('usuarios', '0006_merge_20230703_1958'),
        ('usuarios', '0006_merge_20230704_1554'),
        ('usuarios', '0007_deslikes_date_favoriteslist_date_likes_date_and_more'),
    ]

    operations = [
    ]
